version: "3"

services:
  mysql:
    container_name: mysql
    image: hkccr.ccs.tencentyun.com/buildx/hub:mysql-5.7
    restart: always
    privileged: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./single/my.cnf:/etc/mysql/my.cnf
      - ./single/logs:/var/log/mysql
      - ./single/data:/var/lib/mysql
